### PR TITLE
Working codegen

### PR DESCRIPTION
**Pull request by deavmi**
YEEHAW!

### CODE REVIEW

**Comment by deavmi** [comment]
You might want to discuss make files and stuff as the directory structure here is one I prefer for code gen. specifically.

@Skippy404

**Review by skiqqy — CHANGES_REQUESTED** [review]
I will merge, if you can just refactor the codegen.c and codegen.h files to the src dir, also please update the .gitignore with the appropriate things

**Review by skiqqy — CHANGES_REQUESTED** [review]
remove the binaries please

**Comment by skiqqy** [comment]
I will update the Makefile later for codegen

**Pull request merged**
